// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWWK5Rsc8CiHIp4sleTs5T2uKu7Cjadw',
    appId: '1:246068270577:web:ce6e8145f2616b8d3b2050',
    messagingSenderId: '246068270577',
    projectId: 'evently-app-c13-sat-7pm',
    authDomain: 'evently-app-c13-sat-7pm.firebaseapp.com',
    storageBucket: 'evently-app-c13-sat-7pm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sA3JyYX9XYJ_ibrOjnNQ5inNELPGwRQ',
    appId: '1:246068270577:android:1e9d0ac77b2987373b2050',
    messagingSenderId: '246068270577',
    projectId: 'evently-app-c13-sat-7pm',
    storageBucket: 'evently-app-c13-sat-7pm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu49toZhEcaR3qAN8lEc_Gqmz-9vOpVlA',
    appId: '1:246068270577:ios:b019f04354bcdb3b3b2050',
    messagingSenderId: '246068270577',
    projectId: 'evently-app-c13-sat-7pm',
    storageBucket: 'evently-app-c13-sat-7pm.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppC13Sat7pm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu49toZhEcaR3qAN8lEc_Gqmz-9vOpVlA',
    appId: '1:246068270577:ios:b019f04354bcdb3b3b2050',
    messagingSenderId: '246068270577',
    projectId: 'evently-app-c13-sat-7pm',
    storageBucket: 'evently-app-c13-sat-7pm.firebasestorage.app',
    iosBundleId: 'com.example.eventlyAppC13Sat7pm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWWK5Rsc8CiHIp4sleTs5T2uKu7Cjadw',
    appId: '1:246068270577:web:3f22920cc1e7e42d3b2050',
    messagingSenderId: '246068270577',
    projectId: 'evently-app-c13-sat-7pm',
    authDomain: 'evently-app-c13-sat-7pm.firebaseapp.com',
    storageBucket: 'evently-app-c13-sat-7pm.firebasestorage.app',
  );

}